language: scala
scala: 2.12.7
jdk: openjdk8

stages:
  - name: test
  - name: publish
    if: NOT type = pull_request

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "IRt7GDOT3i/ZSJXuLWXGtXRVboh8fM2hSUoU+c9ACZdfwDQthoZey9EiKV06V9isViyveDb9paMYWJJ+xlLISSfUtvAyvkpnQruQWxYWye4NcLS9+odwUwGXV4/FzU/crehzP+ygAbf+yVzODLivoMACW2r6EtVn1roAQ6YRm+NoqX083y4TilqO+fWzCMIZQgwGUtvEZhGZS/eHcAtJFWpzsUfcOv5OPOZG0dRstTsq3hx9QoEA0Vw0+WNIsg0bh+y4ml2f/TWoz56XIhC8jLeO+8+ThIiBqEgtTHXFXZgbqqyAQJW5XcUA+4575NulGHzNlg8g8BeluK+lHe1cbukJ8wkl4anAPhr0l3tVNw1Y17pDDpygHzO7Y1dNpAQ56oLJf8WztlC+SJ/01n4YIi3TlwlBwHnhM3WX1qkYF6G/MHO47EvZbQi87kHYMp762MpRndmXWSzvulhR9cxk5jUe3LuTUeAYqfYnagJrCrnWOn1p0lAjhy3Ap29xbRiWVRIr5oT1rBZvWtLRdDfx72RguYl5Rx0HuEI2sERnSsEcMySKczPDFZ+E/zibRkQppKPXA/R4nLth/v/Y/iC4M4h2pIVEY+ZlRQhpp2/8t6SCCwdQ5jvYoU7kjdvefxKWNXGue2YsqL/9KdSGxJF+GozMCFG4LCpWkVlGwtG0JGY="
    # GITHUB_TOKEN
    - secure: "sv85gD7j2xQSCx+shDoJJAIeqrflty3Te7HXX7/lISp2lzOunIwfg1K8u2QV01Vb4ik3t23M8kWp17iXPF4v3E1wjibE1y5TXeAjMoQX8NLpybsdvknjPvCjNc7d8j884MC+X2yUt0FPSmox75nMl6yHkma6UG61lVPlqkq2uzFKbxGe0Ys2Ve+JycUF4lMnkLpTflCQpkuo9dqyOT9cDo+RzbV0TEcV/nDUsiJ9wvdd719cFxpAox85IiFWgT7WK1j796U0RTyNnnlBP8Qde0K95W+N+0Y2Dm1ZHv10RnrhU8K9KrPDvgYN3sdmnguyAOl0zXMSFAWtRlYOvqNtj5+u6s1URlQ5NEXIX/4zV6lL/oxkOGzzqANk/ByI66NzcpqwnT+T47vH0M0cYmPjpnxpJZI0Quf9SUPER2persye+u90vvAdLqT3GB8JLTXTX7NSAa0x9QWANAnlanOe+meyZ0Bw+FJydUCQMArK+2TFkxeBagFETy3w9v9AnVOuDlQyHjM9jkW3Iy4C+73Qx99Ta/vZnxKW4phynj8/yugbUCvPGqTgXB1htfPTHWxVxlqyTU3J2bLg/0lkzPOg2dPhlYPL3VyQeLn+8kPIK7gBW8mhRhOkBjl26Wz+3Igdvdy88nWo3XUD+uQfKYqw6GaLTh3t+N7zbM/i2LQaooA="
    # GITHUB_ACCESS_TOKEN
    - secure: "M4rIve0eg3SqA4eULImsH1kxSWsA6VcQG2G9BpylPSjGya7h5k+MaLee9o3lIUWK72fSRNAq9v4mzSaYpklYJ2YlxE3K9YsbXCC+7PlItuFDt9wN7xXde/Mlx2WYcZmK5laHA4npHJ8qHx44e6A4/pJULbUZ/krLeflPvMvqcPYkNYfA++KZXnkiGpcwHmpaRTwAhC1e+JvZ43oqeZoBmGYiEP0hOPmsMq0bW0GYSuVGBML3SWRCz//vuLeD/sWle0peG0hiwZyDIoEEHsRsGoMpWLS67WzDaC+i/d7YCCVBXnhJaniSC6cvYnlV3PzRuums8b3QhabPntsOh/vW/MLa31KOveA1VWpeuDwrbCp5anHVkIniXErgQbfpcOxzrDZWzEyr+J4dDI6rZOcXrv2VuHKRZ9QMSXFRpJiX4gcrEN0OaTvzdyP7RXoFc33FL4DPWksddp6tnDuc5jDVg9itkdR4LaPJ1rEOFavFXqRVIMvc4+uMBFZ/tM1ZQv257VJOHxtxUTLnGs4IJ1yK/uBHX0qshJ1FygkWxmlgxiV/GZQLxhYbfHozvTNfZdKK6qgMUd77W9e/uBE+W21m8LdjbexBfNZw7yoWm/J13TxpemPipmMd+Gl39KXlCv3Ahu5FByFVL2lrlUsMQFW4ad/MkqR5NgChpJ4nbLGUZjw="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "vuX4ijkiZNlcaVrYmFkJhVLHZt4aCyqOb7ukAYpSw9W8DJfnvyXG4iQMg9aI0umpJm1IDHmLezhV7ZHBBe+7kfv1Eug0n5b9GTZnlo3TMUnCGwSl3S4Ky822V5CmwtCBr5EzG3ZhhofSNHSZkixEaodBcPXiAQ2TfkHSpiIGpaJIYJJbKpgCItouPPD3nw/HuF6UqD5wLBUvQVoyBObEuqQsPeftsly7tgYtSYsVHtggZXGQx6pfbaFdlLt3CY2VKe8xDbMRVH5BUZUb0IIu7r+Hx1iuIT8KmOuT3XhYrhCypLr07GUoti0YH/GKgxj2hDZgaQFOqE214tO4SB+XGCIdCEDy9OKg6pPqDJ0xzGfozRnxLo48gCGldcfKHoxe/2bgXLvsmwXK/dzuB/sQ3jNS/SmLtyCZ4qZ9KMJGFYIUnuqHogyfz/j2PK5Vi4UM8L1l2CUhwpUIE91MhTRTmNMW8dyHBrj7YWkZlAsGbuGlJyAYASD+36jH8fsZh8r9UuZlNv5yS3plZnPtaT1IQjFBrw+TodkLoW8d90yXAQlgNbL27hL2gzIRyKaIxQuCZ3rrLcp6fUDYm0Wyz+zi5niK8a7Zk0VPVMa0bIn4VIPYOTI8YqVIt7ex96ou/2xh3xJQIOQWYU8hXqVA7MT7xhkwDSbSEMup693BUiWYWxg="

jobs:
  include:
    - stage: test
      script:
        - set -e
        - $SBT ++$TRAVIS_SCALA_VERSION test

    - stage: publish
      env:
      script:
        - set -e
        - $SBT transferPublishAndTagResources
        - TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/quasar-destination-postgres'

      git:
        depth: false

after_success:
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/

before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
